version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    networks:
      - rede_do_meu_projeto_lindo
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - rede_do_meu_projeto_lindo
    volumes:
      - .:/usr/src/

networks:
  rede_do_meu_projeto_lindo:
    driver: bridge

volumes:
  postgres:
